### ISSUE TITLE
Should render a <table>

### ISSUE THREAD

**Issue by camunity** [alimusa970/favLinks#1]
Hey fam great job on the hw lol but you and Alvin both need to render a `<table>` in the Table class instead of this weird spelling error you both sent in 😂

Can you make the change and resubmit? I can give you full credit that way. Also try not to copy and paste code cuz sometimes things don't work out so well haha

**Comment by alimusa970** [comment]
I see the mistake professor. Actually I think I’m the one who messed up I didn’t see that when I was doing the homework. We also helped each other but I messed up my spelling so for that I am sorry. I am correcting it right now. Thank you professor. 


Sent from Yahoo Mail for iPhone


On Friday, November 13, 2020, 12:41 AM, Cameron Flowers <notifications@github.com> wrote:




Hey fam great job on the hw lol but you and Alvin both need to render a <table> in the Table class instead of this weird spelling error you both sent in 😂
 
Can you make the change and resubmit? I can give you full credit that way. Also try not to copy and paste code cuz sometimes things don't work out so well haha
